# Generated by Django 6.1.1 on 2026-09-26 17:08

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageCompletionRequest',
            fields=[
                ('id', models.CharField(default=api.models.generate_str_id, max_length=64, primary_key=True, serialize=False)),
                ('site_id', models.CharField(blank=True, default='', max_length=64)),
                ('site_name', models.CharField(blank=True, default='', max_length=200)),
                ('stage_name', models.CharField(blank=True, default='', max_length=200)),
                ('requested_by_staff_id', models.CharField(blank=True, default='', max_length=64)),
                ('requested_by_staff_name', models.CharField(blank=True, default='', max_length=150)),
                ('requested_at', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('reviewed_at', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='dailylog',
            name='work_level_stage',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='manualexpense',
            name='work_level_stage',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='work_level_stage',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
