# Generated by Django 5.2.12 on 2026-09-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_stagecompletionrequest_dailylog_work_level_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialsetting',
            name='category',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
    ]
