# Generated by Django 5.2.12 on 2026-09-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_materialsetting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='created_at',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
