# Generated by Django 5.2.12 on 2026-09-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_materialrequest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='cgst_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='igst_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='sgst_amount',
            field=models.FloatField(default=0),
        ),
    ]
