# Generated by Django 5.2.12 on 2026-09-29 09:21

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_materialrequest_cgst_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMaintenance',
            fields=[
                ('id', models.CharField(default=api.models.generate_str_id, max_length=64, primary_key=True, serialize=False)),
                ('vehicle_id', models.CharField(blank=True, default='', max_length=64)),
                ('vehicle_name', models.CharField(blank=True, default='', max_length=150)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.CharField(blank=True, default='', max_length=50)),
                ('type', models.CharField(blank=True, default='General Service', max_length=100)),
                ('cost', models.FloatField(default=0)),
                ('odometer_reading', models.FloatField(default=0)),
                ('workshop_name', models.CharField(blank=True, default='', max_length=200)),
                ('bill_number', models.CharField(blank=True, default='', max_length=100)),
                ('next_service_due_date', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='assigned_driver_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='assigned_driver_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fitness_expiry',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, default='Diesel', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expiry',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='odometer',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(blank=True, default='active', max_length=50),
        ),
    ]
