# Generated by Django 5.2.12 on 2026-09-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_vehiclemaintenance_vehicle_assigned_driver_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='expense_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='expense_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='attendance',
            name='expenses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='attendance',
            name='half_day_counts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='attendance',
            name='site_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
