# Generated by Django 5.2.12 on 2026-10-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_attendance_expense_amount_attendance_expense_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='expense_payment_method',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='income_payment_method',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='manualexpense',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
