# Generated by Django 5.2.12 on 2026-10-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_attendance_expense_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='supervisor_salary',
            field=models.FloatField(default=0),
        ),
    ]
