# Generated by Django 5.2.12 on 2026-10-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_dailylog_supervisor_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='employee_salaries',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
