# Generated by Django 5.2.12 on 2026-10-06 16:39

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_dailylog_employee_salaries'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreRoomDispatch',
            fields=[
                ('id', models.CharField(default=api.models.generate_str_id, max_length=64, primary_key=True, serialize=False)),
                ('material_id', models.CharField(blank=True, default='', max_length=64)),
                ('material_name', models.CharField(blank=True, default='', max_length=150)),
                ('quantity', models.FloatField(default=0)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('site_id', models.CharField(blank=True, default='', max_length=64)),
                ('site_name', models.CharField(blank=True, default='', max_length=200)),
                ('work_level_stage', models.CharField(blank=True, default='', max_length=150)),
                ('dispatch_date', models.CharField(blank=True, default='', max_length=50)),
                ('dispatch_time', models.CharField(blank=True, default='', max_length=50)),
                ('driver_id', models.CharField(blank=True, default='', max_length=64)),
                ('driver_name', models.CharField(blank=True, default='', max_length=150)),
                ('vehicle_id', models.CharField(blank=True, default='', max_length=64)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=50)),
                ('transit_cost', models.FloatField(default=0)),
                ('status', models.CharField(default='dispatched', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='materialsetting',
            name='is_store_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materialsetting',
            name='min_stock_alert',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='materialsetting',
            name='stock_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='materialsetting',
            name='store_room_location',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
