# Generated by Django 5.2.12 on 2026-10-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_storeroomdispatch_materialsetting_is_store_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='delivery_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='is_store_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='return_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='store_room_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='store_room_profit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='storeroomdispatch',
            name='delivery_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='storeroomdispatch',
            name='destination_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='storeroomdispatch',
            name='dispatched_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='storeroomdispatch',
            name='per_day_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='storeroomdispatch',
            name='return_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='storeroomdispatch',
            name='start_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='storeroomdispatch',
            name='store_room_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='storeroomdispatch',
            name='store_room_profit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='storeroomdispatch',
            name='total_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storeroomdispatch',
            name='transfer_to_site_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='storeroomdispatch',
            name='transfer_to_site_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='storeroomdispatch',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
