# Generated by Django 5.2.12 on 2026-10-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_materialrequest_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialsetting',
            name='buying_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='materialsetting',
            name='total_purchase_cost',
            field=models.FloatField(default=0),
        ),
    ]
