# Generated by Django 5.2.12 on 2026-10-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_materialsetting_buying_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='expense_paid_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='expense_paid_at',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='attendance',
            name='expense_rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='attendance',
            name='expense_status',
            field=models.CharField(blank=True, default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='attendance',
            name='expense_verified_at',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='attendance',
            name='expense_verified_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
